### ISSUE TITLE
Which URL to open?

### ISSUE THREAD

**Issue by s3lm** [lonelobo0070/Collection-Manager#2]
Sorry, bloody beginner question :/

sudo docker build -t cm_backend ./api
sudo docker create -p 8080:8080 cm_backend
sudo docker build -t cm_frontend ./gui
sudo docker create -p 80:80 cm_frontend

did all of this successfully, which URL do I have to open in my browser?

tried
http://talderwin.de:8080/
http://talderwin.de:80
http://talderwin.de:8080/games
http://talderwin.de/games
can't open. :/

Should open some kind of landing page?

installed docker and dependencies

node --version v10.15.2
npm --version 5.8.0
OS Ubuntu
Browser: Chrome/Firefox

**Comment by lonelobo0070** [comment]
First of all the application is still in development you can find some bugs and features that aren't working yet.

When everything is installed please check if the containers are running
sudo docker ps -a
If not you can start a container by running sudo docker start {id of the container}.

If everything is running you should brows to http://localhost:80

**Comment by s3lm** [comment]
Do I have to start apache2 or nginx? Maybe it is my systemsetup and not your application thats giving me problems.


root@v22017041323447943:/var/www/html/games# docker ps -a

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
085a91a39121        cm_backend          "docker-php-entrypoi…"   2 minutes ago       Created                                 eager_cohen
ba8f61471bc9        cm_frontend         "nginx -g 'daemon of…"   19 minutes ago      Created                                 wonderful_goldberg


localhost:80 opens the apache2 ubuntu default page 

Do I have to put it in /usr/share/ or /var/www/html/?

Activate it in the nginx or apache2 config file?

Thanks a lot in advance

**Comment by lonelobo0070** [comment]
It looks the port 80 is already in use on your Ubuntu.

Two methods to fix this:
- Stop Apache and start the docker container again and try browse to the path
- Create another docker container for the frontend and switch the port to something else then 80
for ex. sudo docker create -p 8888:80 cm_frontend
-p 8888:80 will make the fronend reachable on localhost:8888
